import type { Metadata } from "next";
import "./globals.css";
import Header from './components/Header';
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "interior",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      
      <head>
      <link rel="preconnect" href="https://fonts.googleapis.com"/>
      <link rel="preconnect" href="https://fonts.gstatic.com" />
      <link rel="icon" href="/atom.ico"/>
      <link href="https://fonts.googleapis.com/css2?family=Syne:wght@400..800&display=swap" rel="stylesheet"></link>
      
      </head>
      
      <body>
        <Header/>
        
        {children}
        
        <Footer/>
      </body>
    </html>
  );
}
